name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: KunalLabs
          outputs: |
            dist/snake.svg

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: output
          publish_dir: ./dist
          external_repository: KunalLabs/Readme  
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true

